package processing.schoolLists.matching;

public class Const {
    /**
     * This is a list of strings that aren't countries but the school parsers might <i>think</i> are countries.
     * <p>
     * Basically, it's just a list of states and provinces (with the notable exception of Georgia).
     * <p>
     * Note that this list only uses lowercase letters. All other characters are ignored when checking for matches.
     */
    @SuppressWarnings("SpellCheckingInspection")
    public static final String[] NOT_A_COUNTRY = {
            "alabama",
            "al",
            "alaska",
            "ak",
            "arizona",
            "az",
            "arkansas",
            "ar",
            "california",
            "ca",
            "colorado",
            "co",
            "connecticut",
            "ct",
            "delaware",
            "de",
            "florida",
            "fl",
            // No Georgia — it's a country
            "ga",
            "hawaii",
            "hi",
            "idaho",
            "id",
            "illinois",
            "il",
            "indiana",
            "in",
            "iowa",
            "ia",
            "kansas",
            "ks",
            "kentucky",
            "ky",
            "louisiana",
            "la",
            "maine",
            "me",
            "maryland",
            "md",
            "massachusetts",
            "ma",
            "michigan",
            "mi",
            "minnesota",
            "mn",
            "mississippi",
            "ms",
            "missouri",
            "mo",
            "montana",
            "mt",
            "nebraska",
            "ne",
            "nevada",
            "nv",
            "newhampshire",
            "nh",
            "newjersey",
            "nj",
            "newmexico",
            "nm",
            "newyork",
            "ny",
            "northcarolina",
            "nc",
            "northdakota",
            "nd",
            "ohio",
            "oh",
            "oklahoma",
            "ok",
            "oregon",
            "or",
            "pennsylvania",
            "pa",
            "rhodeisland",
            "ri",
            "southcarolina",
            "sc",
            "southdakota",
            "sd",
            "tennessee",
            "tn",
            "texas",
            "tx",
            "utah",
            "ut",
            "vermont",
            "vt",
            "virginia",
            "va",
            "washington",
            "wa",
            "westvirginia",
            "wv",
            "wisconsin",
            "wi",
            "wyoming",
            "wy",

            // Other US territories and such
            "districtofcolumbia",
            "dc",
            "americansamoa",
            "as",
            "guam",
            "gu",
            "northernmarianaislands",
            "mp",
            "puertorico",
            "pr",
            "usvirginislands",
            "vi",

            // Other stuff
            "ontario",
            "quebec"
    };

    /**
     * A list of U.S. state and territory abbreviations, designed to match normalized states.
     * <p>
     * Note that this list only uses lowercase letters. All other characters are ignored when checking for matches.
     */
    public static final String[] STATE_ABBREVIATIONS = {
            "AL",
            "AK",
            "AZ",
            "AR",
            "CA",
            "CO",
            "CT",
            "DE",
            "FL",
            "GA",
            "HI",
            "ID",
            "IL",
            "IN",
            "IA",
            "KS",
            "KY",
            "LA",
            "ME",
            "MD",
            "MA",
            "MI",
            "MN",
            "MS",
            "MO",
            "MT",
            "NE",
            "NV",
            "NH",
            "NJ",
            "NM",
            "NY",
            "NC",
            "ND",
            "OH",
            "OK",
            "OR",
            "PA",
            "RI",
            "SC",
            "SD",
            "TN",
            "TX",
            "UT",
            "VT",
            "VA",
            "WA",
            "WV",
            "WI",
            "WY",
            "DC",
            "AS",
            "GU",
            "MP",
            "PR",
            "VI"
    };
}
